apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-test
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: verchinskiymax@gmail.com
    privateKeySecretRef:
      name: letsencrypt-test-private-key
    solvers:
      - http01:
          ingress:
            ingressClassName: alb
            annotations:
              alb.ingress.kubernetes.io/scheme: internet-facing