apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Chart.Name }}-pvc
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - {{ .Values.pv.accessMode }}
  storageClassName: efs-sc
  resources:
    requests:
      storage: {{ .Values.pv.capacity }}