apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secret
type: Opaque
stringData:
  DATABASE_URL: {{ printf "postgres://%s:%s@%s:5432/%s" .Values.secret.DB_USER .Values.secret.DB_PASSWORD .Values.config.HOST .Values.config.DB_NAME | quote }}
  {{- range $key, $value := .Values.secret }}
  {{ $key }}: "{{ $value }}"
  {{- end }}