apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  DATABASE_URL: {{ printf "postgres://%s:%s@%s:5432/%s" .Values.config.DB_USER .Values.secret.DB_PASSWORD .Values.config.HOST .Values.config.DB_NAME | quote }}