apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: my-app-cert
  namespace: {{ .Release.Namespace }}
spec:
  secretName: tls-secret
  issuerRef:
    name: letsencrypt-test
    kind: ClusterIssuer
  commonName: {{ .Values.host }}
  dnsNames:
    - {{ .Values.host }}
