apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Chart.Name }}-cert
  namespace: {{ .Release.Namespace }}
spec:
  secretName: tls-secret
  issuerRef:
    name: {{ .Chart.Name }}-letsencrypt
    kind: ClusterIssuer
  commonName: {{ .Values.host }}
  dnsNames:
    - {{ .Values.host }}
