apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-config
  {{- include "my-lib.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.config }}
  {{ $key }}: "{{ $value }}"
  {{- end }}