- name: Reload systemd daemon
  ansible.builtin.systemd:
    daemon_reload: true

- name: Enable services
  ansible.builtin.systemd:
    name: "{{ item }}"
    enabled: true
  loop: "{{ items }}"

- name: Start services
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: started
  loop: "{{ items }}"
