repositories:
  - name: eks
    url: https://aws.github.io/eks-charts

releases:
  - name: disablak-chart
    namespace: my-space
    chart: ./disablak-chart
    values:
      - disablak-chart/values.yaml
    secrets:
      - disablak-chart/secrets.enc.yaml