- name: kubectl config set-cluster
  ansible.builtin.command:
    argv:
      - kubectl
      - config
      - set-cluster
      - kubernetes-the-hard-way
      - --certificate-authority=ca.crt
      - --embed-certs=true
      - --server=https://server.kubernetes.local:6443
      - --kubeconfig={{ item }}.kubeconfig
    chdir: "{{ path_to_certs }}"
  loop: "{{ elements }}"

- name: kubectl config set-credentials
  ansible.builtin.command:
    argv:
      - kubectl
      - config
      - set-credentials
      - "{{ user }}{{ system }}{{ item }}"
      - --client-certificate={{ item }}.crt
      - --client-key={{ item }}.key
      - --embed-certs=true
      - --kubeconfig={{ item }}.kubeconfig
    chdir: "{{ path_to_certs }}"
  loop: "{{ elements }}"

- name: kubectl config set-context
  ansible.builtin.command:
    argv:
      - kubectl
      - config
      - set-context
      - default
      - --cluster=kubernetes-the-hard-way
      - --user={{ user }}{{ system }}{{ item }}
      - --kubeconfig={{ item }}.kubeconfig
    chdir: "{{ path_to_certs }}"
  loop: "{{ elements }}"

- name: kubectl config use-context
  ansible.builtin.command:
    argv:
      - kubectl
      - config
      - use-context
      - default
      - --kubeconfig={{ item }}.kubeconfig
    chdir: "{{ path_to_certs }}"
  loop: "{{ elements }}"
