- name: Copy file to new location
  ansible.builtin.copy:
    src: "/{{ item }}"
    dest: /usr/local/bin/
    remote_src: true
    mode: '0755'
  loop:
    - etcd
    - etcdctl

# - name: Remove old file
#   ansible.builtin.file:
#     path: "/{{ item }}"
#     state: absent
#   loop:
#     - etcd
#     - etcdctl

- name: Ensure folders exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - /etc/etcd
    - /var/lib/etcd

- name: Copy ca.crt kube-api-server.key kube-api-server.crt to /etc/etcd/
  ansible.builtin.copy:
    src: "/{{ item }}"
    dest: /etc/etcd/
    remote_src: true
    mode: '0755'
  loop:
    - ca.crt
    - kube-api-server.key
    - kube-api-server.crt

- name: Copy etcd.service to /etc/systemd/system/
  ansible.builtin.copy:
    src: /etcd.service
    dest: /etc/systemd/system/
    remote_src: true
    mode: '0755'

- name: Reload systemd daemon
  ansible.builtin.systemd:
    daemon_reload: true

- name: Enable etcd service
  ansible.builtin.systemd:
    name: etcd
    enabled: true

- name: Start etcd service
  ansible.builtin.systemd:
    name: etcd
    state: started