- name: Generate base64 encryption key
  ansible.builtin.shell: head -c 32 /dev/urandom | base64
  register: encryption_key_raw

- name: Write encryption config file
  ansible.builtin.template:
    src: encryption-config.yaml.j2
    dest: "{{ config_path }}encryption-config.yaml"
  vars:
    encryption_key: "{{ encryption_key_raw.stdout }}"
  delegate_to: localhost

- name: Change ownership
  ansible.builtin.file:
    path: "{{ config_path }}encryption-config.yaml"
    owner: "{{ lookup('env', 'USER') }}"
    mode: '0600'
